
The following have been reloaded with a version change:
  1) gcc/10.2.0 => gcc/13.0.1

Traceback (most recent call last):
  File "/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/c_df_dft_mp2.py", line 46, in <module>
    mo_energy, mo_coeff = mymf.get_bands(kpts)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/scf/khf.py", line 716, in get_bands
    fock = fock + self.get_veff(cell, dm_kpts, kpts=kpts, kpts_band=kpts_band)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/krks.py", line 96, in get_veff
    vj = ks.get_j(cell, dm, hermi, kpts, kpts_band)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/scf/khf.py", line 620, in get_j
    return self.get_jk(cell, dm_kpts, hermi, kpts, kpts_band,
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/scf/khf.py", line 638, in get_jk
    vj, vk = self.with_df.get_jk(dm_kpts, hermi, kpts, kpts_band,
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 750, in get_jk
    vj = df_jk.get_j_kpts(self, dm, hermi, kpts, kpts_band)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df_jk.py", line 75, in get_j_kpts
    mydf.build(kpts_band=kpts_band)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 595, in build
    self._make_j3c(self.cell, self.auxcell, kptij_lst, cderi)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 171, in _make_j3c
    outcore._aux_e2(cell, fused_cell, fswap, 'int3c2e', aosym='s2',
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/outcore.py", line 258, in _aux_e2
    feri['%s/%d/%d' % (dataname,k,istep)] = v
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/group.py", line 483, in __setitem__
    ds = self.create_dataset(None, data=obj)
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 168, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 280, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: [Errno 122] Can't synchronously write data (file write failed: time = Fri Dec 15 05:05:39 2023
, filename = '/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/tmp/tmpcobtp6e1', file descriptor = 6, errno = 122, error message = 'Disk quota exceeded', buf = 0x150b616dfdc8, total write size = 1975112, bytes this sub-write = 1975112, bytes actually written = 18446744073709551615, offset = 0)
Exception ignored in: <function H5TmpFile.__del__ at 0x1555404ec9d0>
Traceback (most recent call last):
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/lib/misc.py", line 914, in __del__
    self.close()
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/files.py", line 586, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 360, in h5py.h5f.FileID._close_open_objects
RuntimeError: Disable slist on flush dest failure failed (file write failed: time = Fri Dec 15 05:05:41 2023
, filename = '/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/tmp/tmpcobtp6e1', file descriptor = 6, errno = 122, error message = 'Disk quota exceeded', buf = 0x74502c8, total write size = 180224, bytes this sub-write = 180224, bytes actually written = 18446744073709551615, offset = 0)<exception str() failed>
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
/cm/local/apps/slurm/var/spool/job10633628/slurm_script: line 21: 2117930 Killed                  python c_df_dft_mp2.py $1 $2 $3
slurmstepd: error: Detected 1 oom-kill event(s) in step 10633628.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
