
The following have been reloaded with a version change:
  1) gcc/10.2.0 => gcc/13.0.1

/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/tools/lattice.py:137: UserWarning: Use ase.build.bulk() instead
  ase_atom = bulk('LiF', 'rocksalt', a=4.0351*A2B)
WARNING!
  Very diffused basis functions are found in the basis set. They may lead to severe
  linear dependence and numerical instability.  You can set  cell.exp_to_discard=0.1
  to remove the diffused Gaussians whose exponents are less than 0.1.

Traceback (most recent call last):
  File "/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/lif_df_dft_mp2.py", line 53, in <module>
    mydf.build()
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 595, in build
    self._make_j3c(self.cell, self.auxcell, kptij_lst, cderi)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 171, in _make_j3c
    outcore._aux_e2(cell, fused_cell, fswap, 'int3c2e', aosym='s2',
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/outcore.py", line 258, in _aux_e2
    feri['%s/%d/%d' % (dataname,k,istep)] = v
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/group.py", line 483, in __setitem__
    ds = self.create_dataset(None, data=obj)
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 168, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 280, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: [Errno 122] Can't synchronously write data (file write failed: time = Fri Dec 15 08:04:30 2023
, filename = '/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/tmp/tmp9z2oc8l2', file descriptor = 7, errno = 122, error message = 'Disk quota exceeded', buf = 0x15178ba14d90, total write size = 237568, bytes this sub-write = 237568, bytes actually written = 18446744073709551615, offset = 0)
Exception ignored in: <function H5TmpFile.__del__ at 0x1555404ec9d0>
Traceback (most recent call last):
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/lib/misc.py", line 914, in __del__
    self.close()
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/files.py", line 586, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 360, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
